// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package register

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserSaver creates a new instance of MockUserSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserSaver {
	mock := &MockUserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserSaver is an autogenerated mock type for the UserSaver type
type MockUserSaver struct {
	mock.Mock
}

type MockUserSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserSaver) EXPECT() *MockUserSaver_Expecter {
	return &MockUserSaver_Expecter{mock: &_m.Mock}
}

// SaveUser provides a mock function for the type MockUserSaver
func (_mock *MockUserSaver) SaveUser(ctx context.Context, email string, pasHash []byte) (int64, error) {
	ret := _mock.Called(ctx, email, pasHash)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (int64, error)); ok {
		return returnFunc(ctx, email, pasHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) int64); ok {
		r0 = returnFunc(ctx, email, pasHash)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, email, pasHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserSaver_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUserSaver_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - pasHash []byte
func (_e *MockUserSaver_Expecter) SaveUser(ctx interface{}, email interface{}, pasHash interface{}) *MockUserSaver_SaveUser_Call {
	return &MockUserSaver_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, email, pasHash)}
}

func (_c *MockUserSaver_SaveUser_Call) Run(run func(ctx context.Context, email string, pasHash []byte)) *MockUserSaver_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserSaver_SaveUser_Call) Return(n int64, err error) *MockUserSaver_SaveUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserSaver_SaveUser_Call) RunAndReturn(run func(ctx context.Context, email string, pasHash []byte) (int64, error)) *MockUserSaver_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}
